# Generated by Django 5.2.2 on 2025-06-08 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autor", models.CharField(max_length=100)),
                ("editorial", models.CharField(max_length=100)),
                ("stock_disponible", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Socio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("fecha_alta", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_prestamo", models.DateField(auto_now_add=True)),
                ("fecha_devolucion", models.DateField()),
                ("renovaciones", models.PositiveIntegerField(default=0)),
                ("devuelto", models.BooleanField(default=False)),
                (
                    "libro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="SPB.libro"
                    ),
                ),
                (
                    "socio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="SPB.socio"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Multa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=8)),
                ("fecha_multa", models.DateField(auto_now_add=True)),
                ("estado", models.CharField(default="Pendiente", max_length=20)),
                (
                    "prestamo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="SPB.prestamo"
                    ),
                ),
                (
                    "socio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="SPB.socio"
                    ),
                ),
            ],
        ),
    ]
