# Generated by Django 5.2.2 on 2025-06-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("autor", models.CharField(max_length=255)),
                ("isbn", models.CharField(max_length=20, unique=True)),
                ("editorial", models.CharField(max_length=255)),
                ("anio", models.PositiveIntegerField()),
                ("categoria", models.CharField(max_length=100)),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "portada",
                    models.ImageField(blank=True, null=True, upload_to="portadas/"),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("disponibles", models.PositiveIntegerField(default=1)),
                ("prestados", models.PositiveIntegerField(default=0)),
                ("danados", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
