# Generated by Django 5.2.2 on 2025-06-14 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("libros", "0001_initial"),
        ("socios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_prestamo", models.DateField(auto_now_add=True)),
                ("fecha_devolucion_estimada", models.DateField()),
                ("fecha_devolucion_real", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("vencido", "Vencido"),
                            ("finalizado", "Finalizado"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("renovado", models.BooleanField(default=False)),
                (
                    "libro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestamos",
                        to="libros.libro",
                    ),
                ),
                (
                    "socio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestamos",
                        to="socios.socio",
                    ),
                ),
            ],
        ),
    ]
